name: Coverage
on:
  push:
  pull_request:
  schedule:
    - cron: 0 5 1 */2 *
concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
env:
  NODE_ENV: development
jobs:
  run:
    name: Node ${{ matrix.node }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        node: [ 18, 20, 22, 23 ]
        os: [ ubuntu-latest ]
    steps:
      - name: Clone repo
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - name: Install deps
        run: npm install
      - name: Run tests
        run: npm run test:cover
